#!/bin/sh
#
# copy is a wrapper around rsync to move dotfiles around

set -eu

git ls-files \
| grep -v '^\.gitignore$' \
| grep '^\.' \
| {
	if [ $# -ge 2 ]
	then
		rsync -Eti --ignore-missing-args --files-from - "$@"
	else
		cat
	fi
}