#!/bin/sh

# hostpatch is a simple awk based text preprocessor to
# aid with host specific settings management
# ex: to substitute dotfiles in $HOME run ./hostpatch ~

set -eu

root="${1:?first argument must be a target directory to patch, ex. ~}"

./copy | while read f
do
	f="$root/$f"
	awk '/^#= / {system(substr($0, 4)); next} // { printf "%s%s", $0, RT }' < "$f" > "$f".patched
	cat "$f".patched > "$f"
	rm "$f".patched
done
