#!/bin/sh

set -eu

cd "$(dirname "$0")"

run_files() {
	git ls-files | grep -v \
		-e .gitignore \
		-e manage \
		-e backup
}

run_sync() {
	run_files | rsync --ignore-missing-args --files-from - "$@"
}

cmd="$1"; shift 1
run_"$cmd" "$@"
