#!/bin/sh

set -eu

cd "$(dirname "$0")"

files() {
	git ls-files | grep -v \
		-e '\.in.sh$' \
		-e .gitignore \
		-e sync \
		-e hostpatch \
		-e backup
}

if [ $# -eq 0 ]
then
	files
else
	: "${2:?specify target and source directories}"
	files | rsync --ignore-missing-args --files-from - "$@"
fi
