#!/bin/sh

# sync is a thin wrapper around rsync to move your dotfiles around
# ex: to copy dotfiles from this repo to $HOME run ./sync . ~
# ex: to list dotfiles, that will be copied run ./sync (w/o arguments)

set -eu

cd "$(dirname "$0")"

files() {
	git ls-files \
		| grep '^\.' \
		| grep -v '^\.gitignore$'
}

if [ $# -eq 0 ]
then
	files
else
	: "${2:?specify target and source directories}"
	files | rsync --ignore-missing-args --files-from - "$@"
fi
