#!/bin/sh

set -eu

void_updates() {
	_updates=/tmp/void-updates
	xbps-install -Mun | cut -d' ' -f1 | sed -r 's/-[^-]+$//g' > "$_updates"
	_notable_updates=$(grep -Fxf - <<-'PACKAGES' "$_updates" || true
	bash
	chromium
	firefox
	go
	grub
	linux
PACKAGES
	)

	_total_updates="$(wc -l < "$_updates")"
	printf '%s ' $_notable_updates
	printf '%s packages\n' "$_total_updates"
}

while :
do
	printf 'running\n\4\n'
	void_updates
	printf '\4\n'
	sleep 30m
done
